name: neorg-shortcuts
parent: default

matches:
  - triggers: [":block:", ":nb:"]
    replace: |-
      @code$|$
      @end
    force_clipboard: true

  - triggers: [":code:", ":mc:"]
    replace: |-
        `$|$`
    force_clipboard: true

  - trigger: ":h1:"
    replace: "*"

  - trigger: ":h2:"
    replace: "**"

  - trigger: ":h3:"
    replace: "***"

  - trigger: ":h4:"
    replace: "****"

  - trigger: ":h5:"
    replace: "*****"

  - trigger: ":h6:"
    replace: "******"

  - trigger: ":bold:"
    replace: "*$|$*"

  - trigger: ":italic:"
    replace: "/$|$/"

  - trigger: ":underline:"
    replace: "_$|$_"

  - trigger: ":strike:"
    replace: "-$|$-"

  - trigger: ":url:"
    replace: "[$|$]{}"

  - trigger: ":linkf:"
    replace: "{/ $|$}"
    label: Link to external files

  - trigger: ":linknf:"
    replace: "{:$|$:}"
    label: Link to files within neorg

  - triggers: [":task:", ":mt:"]
    replace: "- ( ) "

  - triggers: [":taskdone:", ":mtd:"]
    replace: "- (x) "
