[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
ignore = ["src/oldstuff"]
stubPath = "src/stubs"
venvPath = "/home/govind/.pyenv/versions/"
venv = "atlas"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.6"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "src" }
]

[tool.flake8]
max-line-length = 120
extend-ignore = "E0101,E0213,E1101,E1102,E1111,E1136,C0103,C0114,C0115,C0116,C0202,C0415,W0105,W0212,W0613,W0622,R0903,R0913,R1720"
max-complexity = 10

[tool.pylint]
max-line-length = 120
extend-ignore = "E0101,E0213,E1101,E1102,E1111,E1136,C0103,C0114,C0115,C0116,C0202,C0415,W0105,W0212,W0613,W0622,R0903,R0913,R1720"

[tool.autopep8]
max_line_length = 120
ignore = ""
aggressive = 2

[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''
target-version = ['py37']
