# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["~/.config/alacritty/themes/themes/github_dark.toml"]

[shell]
program = "/bin/zsh"
args = ["--login"]

[window]
decorations = "None"
opacity = 1
option_as_alt = "Both"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "Maple Mono"
style = "Bold"

[font.italic]
family = "Maple Mono"
style = "Italic"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"
